### Get all posts
GET http://localhost:3000/post
### Add post
POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "First Post",
    "content": "Hello World",
    "sender": "123"
}

GET http://localhost:3000/post