
### POSTS API REQUESTS 

### Add post
POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "This is a post",
    "content": "Hello World",
    "sender": "123"
}

### Get all posts
GET http://localhost:3000/post


### Get a specific post by ID
GET http://localhost:3000/post/69749ca2399c81de26ed1699

### Get a specific post by sender ID
GET http://localhost:3000/post?sender=123

### Update a specific post
PUT http://localhost:3000/post/69749ca2399c81de26ed1699
Content-Type: application/json

{
    "title": "New Title for the Post",
    "content": "This content has been changed!"
}



### COMMENTS API REQUESTS 
### Add a New Comment
POST http://localhost:3000/comment
Content-Type: application/json

{
    "content": "Hello, this is a comment.",
    "sender": "123",
    "postId": "69749ca2399c81de26ed1699" 
}

### Get All Comments
GET http://localhost:3000/comment

### Get a Comment by ID
GET http://localhost:3000/comment/69749ced399c81de26ed169f

### Get Comments by Post ID
GET http://localhost:3000/comment/post/69749ca2399c81de26ed1699

### Update a Comment
PUT http://localhost:3000/comment/69749ced399c81de26ed169f
Content-Type: application/json

{
    "content": "This is the updated comment content."
}

### Delete a Comment
DELETE http://localhost:3000/comment/69749ced399c81de26ed169f

